# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 全栈航行日志 - demax's full stack voyage log
email: demaxism[^.^]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  摸索中的全栈开发者，~2006 上海, ~2009 京都, 至今 东京；
  开发工作涉及游戏，金融； 爱好90年代16位机游戏，FX（主要USD/JPY），公路自行车 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://demaxism.github.io" # the base hostname & protocol for your site
twitter_username: demaxism
github_username:  demaxism

# Build settings
markdown: kramdown
#theme: minima
comments: true

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: demaxism 
